
runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  GOOGLE_CLIENT_ID: "109675542541-pflqr31g4qgckrq6hrl5ap8kbg4p6q8q.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_CLOUD_PROJECT: "mireamakeup"
  SERVICE_DOMAIN: "mireamakeup.oa.r.appspot.com"